version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "weblab-angularappbucket"
        BUILD_FOLDER: "dist"
        SONAR_TOKEN: "6e5e99adcf09530147b43d586f74aa2f7e0ecfb8"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo $CODEBUILD_SRC_DIR
        - echo Installing source NPM dependencies...
        - npm install -y npm@latest
        - npm install -g @angular/cli
        - rm package-lock.json
        - npm install -g sonarqube-scanner
        - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.organization=alainhenryt -Dsonar.projectKey=lab-AngularAWS-CICD
  pre_build:
    commands:
        - npm install
        - npm audit fix
  build:
    commands:
        - echo Build started on 'date'
        - ng build
        - ls -l -F
artifacts:
    files:
        - '**/*'
    type: zip
    discard-paths: yes
    base-directory: 'dist/'
cache:
    paths:
        - node_modules/